org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=1.21.10-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.0-SNAPSHOT

mod.authors=Fuzs
mod.description=Allows for providing defaults for files absent in .minecraft like configs. A quintessential modpack utility.
mod.group=fuzs.configureddefaults
mod.id=configureddefaults
mod.license=MPL-2.0
mod.name=Configured Defaults
mod.version=21.10.0

distributions.curseforge.id=930131
distributions.curseforge.slug=configured-defaults
distributions.github.slug=configureddefaults
distributions.modrinth.id=SISoSFPP
distributions.modrinth.slug=configured-defaults

environments.client=required
environments.server=unsupported
